### ISSUE TITLE
question about translation file

### ISSUE THREAD

**Issue by Vuurvlieg** [AlexandruDoda/Wordboot#1]
First of all, thanks for creating this nice project. This will help me to understand WordPress (plugins).

So I got a question about the way of writing a piece of code inside the [translation file](https://github.com/AlexandruDoda/Wordboot/blob/master/wordboot/includes/setup/class-wordboot-translation.php).

Sorry if I'm wrong but Instead of writing `dirname(dirname(plugin_basename(__FILE__)))` it is better to use `$this->plugin['url']`

So i.e.

`load_plugin_textdomain($this->plugin['id'], false, dirname(dirname(plugin_basename(__FILE__))).'/languages/');`

replace with

`load_plugin_textdomain($this->plugin['id'], false, $this->plugin['url'].'languages/');`

**Comment by AlexandruDoda** [comment]
Hey @Vuurvlieg,

Thanks for pointing that out! I think it's a leftover from early prototyping. I will address that soon.

Cheers!
Alexandru!

**Comment by Vuurvlieg** [comment]
Thanks for your reply.

I don't see any other issues at the moment but got a suggestion tho.

I prefer to keep HTML and PHP separated much as possible. So for my plugin I created a folder called "templates" inside the "admin" folder. In the template folder I put my HTML code for each page. So i.e.
I have template files called `home.php`, `settings.php`,  `about.php` & `404.php`.

Inside the [admin class](https://raw.githubusercontent.com/AlexandruDoda/Wordboot/master/wordboot/includes/admin/class-wordboot-admin.php) I write something like

<a href="http://nl.tinypic.com?ref=30shzep" target="_blank"><img src="http://i64.tinypic.com/30shzep.png" border="0" alt="Image and video hosting by TinyPic"></a>

This way the HTML and PHP are separated much as possible (Ofcourse a template file could make use of some little bit of PHP).

So such method might be used inside Wordboot, but if you know a nicer way I like to hear it :)

**Comment by AlexandruDoda** [comment]
All right, I see! So it looks like you are registering plugin settings. There is a class already included for that called **[class-wordboot-settings.php](https://github.com/AlexandruDoda/Wordboot/blob/master/wordboot/includes/admin/class-wordboot-settings.php)** that helps with field creation and all that, but right now it's only accommodated for a main settings page.

If you wish to create multiple pages as outlined in your screenshot, it's a good suggested approach. My only note would be to do these in the settings class that I pointed to above. 

Cheers!
Alexandru
